# Copy this file to config.yml to get started and then add your own configuration.
# Full documentation here: https://github.com/CryptoSignal/crypto-signal/blob/master/docs/config.md

settings:
  update_interval: 60
  market_pairs:
    - BTC/USDT
    - ETH/USDT

exchanges:
  bittrex:
    required:
      enabled: true
